apiVersion: v1
kind: Service
metadata:
  name: log
  labels:
    app: log
    component: log
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: log-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log
    component: log
